---
- name: Execute sql script
  hosts: dboracle21.localdomain
  tasks:
  - name: Create temp directory {{ tmp_path }}
    file: 
      path: "{{ tmp_path }}"
      state: directory
      owner: "oracle" 
      group: "oinstall"
      mode: 0755
    become: true
    become_method: su
    become_user: oracle
    become_exe: 'sudo su -'

  - name: Execute sql script
    shell: "$ORACLE_HOME/bin/sqlplus -s mvega/x@ORCLPDB1 @/scripts/oracle/R_blocking_session_mnpt.sql {{ c_sid }} {{ c_blocking }} {{ sql_id }} {{ tmp_path }}"
    environment: 
      ORACLE_HOME: "/opt/oracle/product/21c/dbhome_1"
      PATH: "/opt/oracle/product/21c/dbhome_1/bin"
    args:
      chdir: "/scripts" 
    become: true
    become_method: su
    become_user: oracle
    become_exe: 'sudo su -'

  - name: Create zip fil with the output
    archive:
      path: 
        - '{{ tmp_path }}'
      dest: /tmp/output.zip
      format: zip

  - name: Attach a file
    community.general.jira:
      uri: '{{ jiraServer }}'
      username: '{{ jiraUser }}'
      password: '{{ jiraPass }}'
      issue: TEST-1
      operation: attach
      attachment:
        filename: /tmp/output.zip      

  - name: Comment on issue
    community.general.jira:
      uri: '{{ jiraServer }}'
      username: '{{ jiraUser }}'
      password: '{{ jiraPass }}'
      issue: TEST-1
      operation: comment
      comment: "A comment added by Ansible: PFA"

  - name: Remove temp directory {{ tmp_path }}
    file: 
      path: "{{ tmp_path }}"
      state: absent
    become: true
    become_method: su
    become_user: oracle
    become_exe: 'sudo su -'

  - name: Remove zip file with results
    file: 
      path: "/tmp/output.zip"
      state: absent
    become: true
    become_method: su
    become_user: oracle
    become_exe: 'sudo su -'